name: portafolio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask
  - mysql-connector-python
  - werkzeug
  - sendgrid
  - python-dotenv
  - pylint
  - ipython
variables:
  FLASK_APP: src
